name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:   
    - name: Auto Author Assign
      uses: toshimaru/auto-author-assign@v2.1.1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto asign reviewers
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ISIS3510-TEAM-XX/android
